#!/bin/bash

# 2021 - Romain RICARD
# See license at https://github.com/romainricard/jq-wrappers/blob/main/LICENSE

set -euo pipefail

help(){
    echo "$0: Format then open two minified JSON file into diff."
    echo
    echo "Usage: $0 <input JSON file 1> <input JSON file 2>"
}

err(){
    echo
    echo "Error: $1"
}


if [ $# -eq 0 ]; then
    help
    err "No JSON file supplied."
    exit 1
fi

if [ ! -f $1 ] || [ ! -f $2 ]; then
    help
    err "The supplied file does not exist.";
    exit 1;
fi


diff <(jq . < $1)  <(jq . < $2)
